/**
 * Central site configuration: identity, links and SEO defaults.
 * Page content lives in lib/resume.ts and lib/projects.ts.
 */

export const siteConfig = {
  /** Set NEXT_PUBLIC_SITE_URL when you deploy (e.g. https://nirmal.dev). */
  url:
    process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ??
    "https://example.com",

  name: "Nirmal Maharjan",
  /** Short title used in the hero, page titles and Person JSON-LD. */
  title: "Frontend Developer",
  /** Default meta description. */
  description:
    "Frontend developer in Kathmandu, Nepal, building production websites, landing pages and CMS dashboards with Next.js, TypeScript and React.",
  /** Search keywords for the homepage. */
  keywords: [
    "Frontend Developer Nepal",
    "Frontend Developer Kathmandu",
    "Next.js Developer Nepal",
    "React Developer Kathmandu",
    "TypeScript",
    "Tailwind CSS",
    "Nirmal Maharjan",
  ],

  location: "Kathmandu, Nepal",
  availability: "Open to new opportunities",
  /** What you're looking for; shown in the hero and on the contact card. */
  // TODO: confirm the kind of role you want.
  lookingFor: "Full-time frontend roles, remote or in Kathmandu",
  timezone: "UTC+5:45",
  /** Years of frontend experience, used in the hero, facts row and ledger. */
  experienceYears: "1.5+",

  /** Served from /public. Replace the file to update your CV. */
  resumeUrl: "/resume.pdf",
  resumeFileName: "Nirmal-Maharjan-Resume.pdf",

  locale: "en_US",
  /** Default OG image, generated by app/opengraph-image.tsx. */
  ogImage: "/opengraph-image",

  author: {
    name: "Nirmal Maharjan",
    email: "nirmalmhjr@gmail.com",
    github: "nirmalmhjr",
    /** Add your LinkedIn handle to show it in the header, footer and contact page. */
    // linkedin: "https://www.linkedin.com/in/nirmal-maharjan-513290a9/",
    linkedin: "nirmal-maharjan-513290a9/",
  },

  /** Posts per page on the blog listing. */
  postsPerPage: 6,
} as const;

export const socialLinks = {
  email: `mailto:${siteConfig.author.email}`,
  /** Email link with a subject line, for "Email me" buttons. */
  hireEmail: `mailto:${siteConfig.author.email}?subject=${encodeURIComponent(
    "Frontend developer role"
  )}`,
  github: `https://github.com/${siteConfig.author.github}`,
  linkedin: siteConfig.author.linkedin
    ? `https://www.linkedin.com/in/${siteConfig.author.linkedin}`
    : null,
} as const;

export const mainNav = [
  { title: "Projects", href: "/projects" },
  { title: "About", href: "/about" },
  { title: "Blog", href: "/blog" },
  { title: "Uses", href: "/uses" },
  { title: "Contact", href: "/contact" },
] as const;

/** Absolute URL helper. Pass a path with a leading slash. */
export function absoluteUrl(path = "/"): string {
  return `${siteConfig.url}${path.startsWith("/") ? path : `/${path}`}`;
}
