/**
 * Central site configuration: identity, links and SEO defaults.
 * Page content lives in lib/resume.ts and lib/projects.ts.
 */

export const siteConfig = {
  /** Set NEXT_PUBLIC_SITE_URL when you deploy (e.g. https://nirmal.dev). */
  url:
    process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ??
    "https://example.com",

  name: "Nirmal Maharjan",
  /** Short title used in the hero, page titles and Person JSON-LD. */
  title: "Frontend Developer",
  /** Default meta description. */
  description:
    "Frontend developer in Kathmandu building fast, responsive websites, landing pages and CMS dashboards with Next.js and TypeScript.",

  location: "Kathmandu, Nepal",
  availability: "Open to new opportunities",
  /** Shown in the hero credentials line and the ledger total. */
  experience: "1.5+ years",

  /** Served from /public. Replace the file to update your CV. */
  resumeUrl: "/resume.pdf",
  resumeFileName: "Nirmal-Maharjan-Resume.pdf",

  locale: "en_US",
  /** Default OG image, generated by app/opengraph-image.tsx. */
  ogImage: "/opengraph-image",

  author: {
    name: "Nirmal Maharjan",
    email: "nirmalmhjr@gmail.com",
    github: "nirmalmhjr",
    /** Add your LinkedIn handle to show it in the header, footer and contact page. */
    linkedin: "",
  },

  /** Posts per page on the blog listing. */
  postsPerPage: 6,
} as const;

export const socialLinks = {
  email: `mailto:${siteConfig.author.email}`,
  github: `https://github.com/${siteConfig.author.github}`,
  linkedin: siteConfig.author.linkedin
    ? `https://www.linkedin.com/in/${siteConfig.author.linkedin}`
    : null,
} as const;

export const mainNav = [
  { title: "Projects", href: "/projects" },
  { title: "About", href: "/about" },
  { title: "Blog", href: "/blog" },
  { title: "Uses", href: "/uses" },
  { title: "Contact", href: "/contact" },
] as const;

/** Absolute URL helper. Pass a path with a leading slash. */
export function absoluteUrl(path = "/"): string {
  return `${siteConfig.url}${path.startsWith("/") ? path : `/${path}`}`;
}
